[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "rt", "sync", "time"] }
