[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2"
bytes = "1"
clap = { version = "4", features = ["derive"] }
quaternion = "2"
quick-xml = { version = "0.37", features = ["serialize"] }
reqwest = "0.12"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "sync",
    "time",
] }
tracing = "0.1"
tracing-subscriber = "0.3"
